N_wetting: 500
R_eq: 3.0
R_init: 2.75
R_ten_factor: 1.5
alpha: 50
eta: 0.5
gamma: 0.8
id: 0
interpolate_cntrs: false
lam: 0.8
mu_mvg: 7.5
nu: 0
perturbation: 0
polarity_mode: IM
sigma_mvg: 37.5
tau: 0.125
tau_mvg: 0.00208
tau_ten: 1.0
tau_x: 0.02
